# Generated by Django 4.0.4 on 2022-04-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
